state = {'apertures':1,
         'apradii':1,
         'apsigns':1,
         'atrans_wave':1,
         'atrans_trans':1,
         'bad_pixel_mask_file': None,
         'badpixelmask':1,
         'bgfitdeg':1,
         'bgradius':1,
         'bgwidth':1,         
         'biasfile':'',
         'continue':0,
         'edgecoeffs':1,
         'edgedeg':1,
         'exttype':None,
         'filereadmode':'',
         'flatfile':None,
         'hdrinfo':1,
         'instruments':['uspex','spex'],
         'instrument_path': '',
         'irtf':False,
         'linearity_info':1,
         'linearity_correction':'',
         'locate_aperture_inputs':1,
         'modename':'',
         'naps':1,
         'ncols':1,
         'nint': 1,
         'norders':1,
         'nrows':1,
         'ordermask':1,
         'orders':1,
         'output_prefix':'spectra',
         'package_path':'',
         'plate_scale':1,
         'prefix':'',
         'profiles':1,
         'psdoorders':1,
         'psfradius':1,
         'qaextension':1,
         'qaextensions':['.pdf','.png'],
         'qafilename':'',
         'rawbadpixelmask':1,
         'rectindices':1,
         'rectorders':1,
         'resolvingpower':1,
         'rotation':1,
         'reductionmode':1,
         'slith_arc':1,
         'slitw_arc':1,
         'slith_pix':1,
         'slitw_pix':1,                 
         'spatcal':1,
         'suffix':'',
         'tracecoefs':1,
         'varimage':1,
         'version':'1beta',
         'wavecal':1,
         'wavecaltype':1,
         'wavecalfile':None,
         'workimage':1,
         'xranges':1,
         'xsdoorders':1}

user = {'setup':{'instrument':'', 'rawpath':'', 'calpath':'', 'procpath':'',
                 'qapath':'', 'instr':'', 'qaextension':'', 'verbose':True},
        'load':{'flatfile':'', 'wavecalfile':'', 'reduction_mode':'',
                'directory':'', 'suffix':'', 'doflat':True, 
                'dolinearity':True, 'qafile':True, 'qaplot':True,
                'verbose':True},
        'extype':{'type':''},
        'profiles':{'qaplot':True, 'qafile':True, 'verbose':True},
        'locateaps':{'apertures':1, 'method':'', 'fwhm':0.8, 'qaplot':False,
                     'qafile':False, 'verbose':True},
        'orders':{'include':'', 'exclude':'', 'include_all':False,
                  'verbose':True, 'qaplot':False, 'qafile':False},
        'trace':{'fitdeg':1, 'step':1, 'sumwidth':1, 'centhresh':1, 'fwhm':1,
                 'verbose':True, 'qaplot':False, 'qafile':False},
        'apparms':{'apradii':1, 'psfradius':1, 'bgradius':1, 'bgwidth':1,
                   'bgregions':1, 'bgdeg':1, 'qaplot':False, 'qafile':False},
        'extract':{'verbose':True}}



