state = {'deconvolution_window':0,
         'model':'',
         'method':'',
         'mode':'',
         'normalization_degree':'',         
         'normalization_windows':'',
         'normalized_order':0,        
         'normalized_order_wavelength':0,
         'normalized_order_flux':0,
         'normalize_plotnumber':None,
         'object_spectra':1,
         'object_hdrinfo':1,
         'object_info':1,
         'object_redshift':0,         
         'object_rv':0,
         'radialvelocity_window':0,
         'standrd_info':1,         
         'standard_spectra':1, 
         'standard_hdrinfo':1,
         'standard_sptype':'A0V',
         'standard_name': 'name',
         'standard_vmag':0.0,
         'standard_bmag':0.0,         
         'spectra_plotnum':None,
         'xcorrelate_plotnum':None,
         'vega_continuum':0,
         'vega_fitted_continuum':0,
         'vega_flux':0,
         'vega_normalized_flux':0,         
         'vega_wavelength':0,
         'yunits':'',
         'latex_yunits':'',
         'latex_ylabel':''}         

load = {'object_file':1, 'standard': 1, 'standard_file':1, 'v_magnitude':1,
        'output_name':1, 'fluxdensity_units':1, 'standard_data':None,
        'reflectance': 1, 'input_path':1, 'output_path':1, 'qa_path':1,
        'qafile':True, 'qaplot':True, 'qaplotsize':(6,6), 'verbose':True,
        'overwrite':True}

