state = {'apertures':1,
         'apsigns':1,
         'atrans_wave':1,
         'atrans_trans':1,
         'badpixelmask':1,
         'biasfile':'',
         'calpath':'',
         'edgecoeffs':1,
         'edgedeg':1,
         'exttype':None,
         'flatfile':None,
         'instruments':['uspex','spex'],
         'instrument':'uspex',
         'irtf':False,
         'linearity_info':1,
         'linearity_correction':'',
         'modename':'',
         'naps':1,
         'ncols':1,
         'nint': 1,
         'norders':1,
         'nrows':1,
         'ordermask':1,
         'orders':1,
         'packagepath':'',
         'procpath':'',
         'plate_scale':1,
         'profiles':1,
         'psdoorders':1,
         'pscontinue': 0,
         'qapath':'',
         'rawbadpixelmask':1,
         'rawpath':'',
         'readfits':'read_uspex_fits',
         'rotation':1,
         'rectorders':1,
         'resolvingpower':1,
         'slith_arc':1,
         'slitw_arc':1,
         'slith_pix':1,
         'slitw_pix':1,                 
         'spatcal':1,
         'suffix':'',
         'version':'1beta',
         'wavecal':1,
         'wavecalfile':None,
         'workfiles':'',
         'workimage':1,
         'xranges':1,
         'xsdoorders':1}



