state = {'bad_pixel_mask':1,
         'biasfile':'',
         'calpath':'',
         'edgecoeffs':1,
         'flat':1,
         'instruments':['uspex','spex'],
         'instrument':'uspex',
         'irtf':False,
         'linearity_info':1,
         'modename':'',
         'ncols':1,
         'nint': 1,
         'norders':1,
         'nrows':1,
         'omask':1,
         'orders':1,
         'packagepath':'',
         'procpath':'',
         'ps':1,
         'psdoorders':1,
         'qapath':'',
         'rawpath':'',
         'rotation':1,
         'rp':1,
         'slith_arc':1,
         'slitw_arc':1,
         'slith_pix':1,
         'slitw_pix':1,                 
         'suffix':'',
         'version':'1beta',
         'workfiles':'',
         'xranges':1,
         'xsdoorders':1}



