state = {'raw_bad_pixel_mask':0,
         'cal_path':'',
         'combine_keywords':'',
         'extract_keywords':'',
         'instrument':'',
         'instruments':['uspex','spex'],         
         'instrument_path':'',
         'irtf':False,
         'lincormax':0,
         'linearity_info':0,
         'nint':4,
         'package_path':'',
         'proc_path':'',
         'pyspextool_keywords':'',
         'qa_path':'',
         'qa_extension':'.pdf',
         'qa_extensions':['.pdf','.png', None],
         'qa_file':True,
         'qa_plot':False,         
         'raw_path':'',
         'suffix':'',
         'telluric_keywords':'',         
         'verbose':True,
         'version':'1beta'}
